name: Makefile

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
     - main

env:
  CARGO_TERM_COLOR: always

jobs:
  make:
    strategy:
      matrix:
        os:
          [
            ubuntu-latest,
            macos-latest,
          ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Install golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.2

    - name: Build
      run: make
